name: 'Build & Deploy Game'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: 'build'
  cancel-in-progress: true
  
jobs:
  build-wgl:
    name: 'Build and deploy WebGL'
    timeout-minutes: 45
    runs-on: [self-hosted, linux]
    environment:
        name: "${{ (contains(github.event.head_commit.message, '[prod]') || github.event_name == 'workflow_dispatch') && 'Production' || 'Development' }}"
        url: "${{ steps.deploy.outputs.url }}"
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Local cache for Library
        id: api-cache-wgl
        uses: MasterworksIO/action-local-cache@1.0.0
        with:
          path: './the-forest-spirits/Library/'
          key: 'Library-wgl'

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./the-forest-spirits

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: build/WebGL

      # Deploy
      - name: Deploy
        id: deploy
        run: |-
          npm install -g vercel
          cd build/WebGL/WebGL
          sudo cp -r ../../../.vercel-for-build ./.vercel
          sudo mv ./.vercel/config.json ./vercel.json
          vercel deploy --token ${{ secrets.JONA_VERCEL_TOKEN }} ${{ (contains(github.event.head_commit.message, '[prod]') && github.event_name != 'workflow_dispatch') && '--prod' || '' }} | tee ${{ runner.temp }}/_OUT_URL.txt
          echo "url=$(cat ${{ runner.temp }}/_OUT_URL.txt)" >> "$GITHUB_OUTPUT"
          rm ${{ runner.temp }}/_OUT_URL.txt
  build-macos:
    if: false
    name: 'Build and upload MacOS'
    timeout-minutes: 45
    runs-on: [self-hosted, macos]
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Local cache for Library
        id: api-cache-macos
        uses: MasterworksIO/action-local-cache@1.0.0
        with:
          path: './the-forest-spirits/Library/'
          key: 'Library-macos'

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          projectPath: ./the-forest-spirits

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-OSX
          path: build/StandaloneOSX
  build-windows:
    if: false
    name: 'Build and upload Windows'
    timeout-minutes: 45
    runs-on: [self-hosted, linux]
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Local cache for Library
        id: api-cache-win
        uses: MasterworksIO/action-local-cache@1.0.0
        with:
          path: './the-forest-spirits/Library/'
          key: 'Library-win'

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: ./the-forest-spirits

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
  build-linux:
    if: false
    name: 'Build and upload Linux'
    timeout-minutes: 45
    runs-on: [self-hosted, linux]
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Local cache for Library
        id: api-cache-linx
        uses: MasterworksIO/action-local-cache@1.0.0
        with:
          path: './the-forest-spirits/Library/'
          key: 'Library-linx'

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
          projectPath: ./the-forest-spirits

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-StandaloneLinux64
          path: build/StandaloneLinux64
