name: 'Build & Deploy WebGL'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: 'build'
  cancel-in-progress: false
  
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./the-forest-spirits

      # Deploy
      - run: |-
          npm install -g vercel
          vercel login --token ${{ secrets.JONA_VERCEL_TOKEN }}
          cd build
          cp -r ../.vercel-for-build ./.vercel
          mv ./.vercel/config.json ./vercel.json
          vercel
      # Output
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: Build
      #    path: build

